module Wovnrb
  module UnifiedValues
    module ElementCategory
      FLOW_CONTENT = 1
      PALPABLE_CONTENT = 2
      PHRASING_CONTENT = 3
      EMBEDDED_CONTENT = 4
      INTERACTIVE_CONTENT = 5
      METADATA_CONTENT = 6
      HEADING_CONTENT = 7
      SECTIONING_CONTENT = 8
      SECTIONING_ROOT = 9
      FORM_ASSOCIATED_ELEMENT = 10
      SCRIPT_SUPPORTING_ELEMENT = 11
      SVG_ELEMENT = 12

      DOCUMENT_ELEMENT = 100
      DOCUMENT_METADATA = 101
      SECTION = 1010
      GROUPING_CONTENT = 103
      TEXT_LEVEL_SEMANTICS = 104
      EDITS = 105
      EMBEDDED_CONTENTS = 106
      LINKS = 107
      TABULAR_DATA = 108
      FORMS = 109
      INTERACTIVE_ELEMENTS = 110
      SCRIPTING = 111
      ESCAPABLE_RAW_TEXT_ELEMENT = 112

      RESTRICTED_TO_CHILD_OF_TEXT_LEVEL_SEMANTICS = 200
      RESTRICTED_TO_CHILD_OF_GROUPING = 201
      RESTRICTED_TO_CHILD_OF_EMBEDDED = 202
      RESTRICTED_TO_CHILD_OF_TABULAR = 203
      RESTRICTED_TO_CHILD_OF_FORM = 204
      RESTRICTED_TO_CHILD_OF_INTERACTIVE = 205

      RESTRICTION_PARENT_ELEMENT = 300
      FORM_OWNER = 301

      # Below will help to know every elements.
      # https://www.w3.org/TR/html5/
      # https://dev.w3.org/html5/html-author/#the-elements
      # https://html.spec.whatwg.org/#elements-2
      #
      # Below will help to know default display of elements.
      # https://html.spec.whatwg.org/#rendering

      # This constant is for internal. SHOULD NOT be used outside this class.
      CONTENT_TYPES = {
        'a' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, INTERACTIVE_CONTENT, PALPABLE_CONTENT],
        'abbr' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'address' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT],
        'area' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT],
        'article' => [SECTION, FLOW_CONTENT, SECTIONING_CONTENT, PALPABLE_CONTENT],
        'aside' => [SECTION, FLOW_CONTENT, SECTIONING_CONTENT, PALPABLE_CONTENT],
        'audio' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENT, INTERACTIVE_CONTENT, PALPABLE_CONTENT],
        'b' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'base' => [DOCUMENT_METADATA, METADATA_CONTENT],
        'bb' => [INTERACTIVE_ELEMENTS, FLOW_CONTENT, PHRASING_CONTENT, INTERACTIVE_CONTENT],
        'bdi' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'bdo' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'blockquote' => [GROUPING_CONTENT, FLOW_CONTENT, SECTIONING_ROOT, PALPABLE_CONTENT],
        'body' => [SECTION, SECTIONING_ROOT],
        'br' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT],
        'button' => [FORMS, FLOW_CONTENT, PHRASING_CONTENT, INTERACTIVE_CONTENT, FORM_ASSOCIATED_ELEMENT, PALPABLE_CONTENT],
        'canvas' => [SCRIPTING, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENTS, PALPABLE_CONTENT],
        'caption' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR],
        'cite' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'code' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'col' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR],
        'colgroup' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR, RESTRICTION_PARENT_ELEMENT],
        'data' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'datalist' => [FORMS, FLOW_CONTENT, PHRASING_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'dd' => [GROUPING_CONTENT, RESTRICTED_TO_CHILD_OF_GROUPING],
        'del' => [EDITS, FLOW_CONTENT, PHRASING_CONTENT],
        'details' => [INTERACTIVE_ELEMENTS, FLOW_CONTENT, SECTIONING_ROOT, INTERACTIVE_CONTENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'dfn' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'dialog' => [INTERACTIVE_ELEMENTS, FLOW_CONTENT, SECTIONING_ROOT],
        'div' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT],
        'dl' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'dt' => [GROUPING_CONTENT, RESTRICTED_TO_CHILD_OF_GROUPING],
        'em' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'embed' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENT, INTERACTIVE_CONTENT, PALPABLE_CONTENT],
        'fieldset' => [FORMS, FLOW_CONTENT, SECTIONING_ROOT, FORM_ASSOCIATED_ELEMENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'figcaption' => [GROUPING_CONTENT, RESTRICTED_TO_CHILD_OF_GROUPING],
        'figure' => [GROUPING_CONTENT, FLOW_CONTENT, SECTIONING_ROOT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'footer' => [SECTION, FLOW_CONTENT, PALPABLE_CONTENT],
        'form' => [FORMS, FLOW_CONTENT, PALPABLE_CONTENT, FORM_OWNER],
        'h1' => [SECTION, FLOW_CONTENT, HEADING_CONTENT, PALPABLE_CONTENT],
        'h2' => [SECTION, FLOW_CONTENT, HEADING_CONTENT, PALPABLE_CONTENT],
        'h3' => [SECTION, FLOW_CONTENT, HEADING_CONTENT, PALPABLE_CONTENT],
        'h4' => [SECTION, FLOW_CONTENT, HEADING_CONTENT, PALPABLE_CONTENT],
        'h5' => [SECTION, FLOW_CONTENT, HEADING_CONTENT, PALPABLE_CONTENT],
        'h6' => [SECTION, FLOW_CONTENT, HEADING_CONTENT, PALPABLE_CONTENT],
        'head' => [DOCUMENT_METADATA],
        'header' => [SECTIONING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT],
        'hgroup' => [SECTION, FLOW_CONTENT, HEADING_CONTENT, PALPABLE_CONTENT],
        'hr' => [GROUPING_CONTENT, FLOW_CONTENT],
        'html' => [DOCUMENT_ELEMENT],
        'i' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'iframe' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENT, INTERACTIVE_CONTENT, PALPABLE_CONTENT],
        'img' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENT, FORM_ASSOCIATED_ELEMENT, INTERACTIVE_CONTENT, PALPABLE_CONTENT],
        'input' => [FORMS, FLOW_CONTENT, PHRASING_CONTENT, INTERACTIVE_CONTENT, FORM_ASSOCIATED_ELEMENT, PALPABLE_CONTENT],
        'ins' => [EDITS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'kbd' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'label' => [FORMS, FLOW_CONTENT, PHRASING_CONTENT, INTERACTIVE_CONTENT, FORM_ASSOCIATED_ELEMENT, PALPABLE_CONTENT],
        'legend' => [FORMS, RESTRICTED_TO_CHILD_OF_FORM],
        'li' => [GROUPING_CONTENT, RESTRICTED_TO_CHILD_OF_GROUPING],
        'link' => [DOCUMENT_METADATA, METADATA_CONTENT, FLOW_CONTENT, PHRASING_CONTENT],
        'main' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT],
        'map' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'mark' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'menu' => [INTERACTIVE_ELEMENTS, FLOW_CONTENT, INTERACTIVE_CONTENT],
        'meta' => [DOCUMENT_METADATA, METADATA_CONTENT],
        'meter' => [FORMS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'nav' => [SECTION, FLOW_CONTENT, SECTIONING_CONTENT, PALPABLE_CONTENT],
        'noscript' => [SCRIPTING, METADATA_CONTENT, FLOW_CONTENT, PHRASING_CONTENT],
        'object' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'ol' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'optgroup' => [FORMS, RESTRICTED_TO_CHILD_OF_FORM, RESTRICTION_PARENT_ELEMENT],
        'option' => [FORMS, RESTRICTED_TO_CHILD_OF_FORM],
        'output' => [FLOW_CONTENT, PHRASING_CONTENT, FORM_ASSOCIATED_ELEMENT, PALPABLE_CONTENT],
        'p' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT],
        'param' => [EMBEDDED_CONTENTS, RESTRICTED_TO_CHILD_OF_EMBEDDED],
        'picture' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENT],
        'pre' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT],
        'progress' => [FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'q' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'rb' => [TEXT_LEVEL_SEMANTICS, RESTRICTED_TO_CHILD_OF_TEXT_LEVEL_SEMANTICS],
        'rp' => [TEXT_LEVEL_SEMANTICS, RESTRICTED_TO_CHILD_OF_TEXT_LEVEL_SEMANTICS],
        'rt' => [TEXT_LEVEL_SEMANTICS, RESTRICTED_TO_CHILD_OF_TEXT_LEVEL_SEMANTICS],
        'rtc' => [TEXT_LEVEL_SEMANTICS, RESTRICTED_TO_CHILD_OF_TEXT_LEVEL_SEMANTICS],
        'ruby' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        's' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'samp' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'script' => [SCRIPTING, METADATA_CONTENT, FLOW_CONTENT, PHRASING_CONTENT, SCRIPT_SUPPORTING_ELEMENT],
        'section' => [SECTION, FLOW_CONTENT, SECTIONING_CONTENT, PALPABLE_CONTENT],
        'select' => [FORMS, FLOW_CONTENT, PHRASING_CONTENT, INTERACTIVE_CONTENT, FORM_ASSOCIATED_ELEMENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'slot' => [SCRIPTING, FLOW_CONTENT, PHRASING_CONTENT],
        'small' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'source' => [EMBEDDED_CONTENTS, RESTRICTED_TO_CHILD_OF_EMBEDDED],
        'span' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'strong' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'style' => [DOCUMENT_METADATA, METADATA_CONTENT, FLOW_CONTENT],
        'sub' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'summary' => [INTERACTIVE_ELEMENTS, RESTRICTED_TO_CHILD_OF_INTERACTIVE],
        'sup' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'svg' => [SVG_ELEMENT],
        'table' => [TABULAR_DATA, FLOW_CONTENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'tbody' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR, RESTRICTION_PARENT_ELEMENT],
        'td' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR],
        'template' => [SCRIPTING, METADATA_CONTENT, FLOW_CONTENT, PHRASING_CONTENT, SCRIPT_SUPPORTING_ELEMENT],
        'textarea' => [FORMS, FLOW_CONTENT, PHRASING_CONTENT, INTERACTIVE_CONTENT, FORM_ASSOCIATED_ELEMENT, PALPABLE_CONTENT, ESCAPABLE_RAW_TEXT_ELEMENT],
        'tfoot' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR, RESTRICTION_PARENT_ELEMENT],
        'th' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR],
        'thead' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR, RESTRICTION_PARENT_ELEMENT],
        'time' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'title' => [DOCUMENT_METADATA, METADATA_CONTENT, ESCAPABLE_RAW_TEXT_ELEMENT],
        'tr' => [TABULAR_DATA, RESTRICTED_TO_CHILD_OF_TABULAR, RESTRICTION_PARENT_ELEMENT],
        'track' => [EMBEDDED_CONTENTS, RESTRICTED_TO_CHILD_OF_EMBEDDED],
        'u' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'ul' => [GROUPING_CONTENT, FLOW_CONTENT, PALPABLE_CONTENT, RESTRICTION_PARENT_ELEMENT],
        'var' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT],
        'video' => [EMBEDDED_CONTENTS, FLOW_CONTENT, PHRASING_CONTENT, EMBEDDED_CONTENT, INTERACTIVE_CONTENT, PALPABLE_CONTENT],
        'wbr' => [TEXT_LEVEL_SEMANTICS, FLOW_CONTENT, PHRASING_CONTENT]
      }.freeze

      # NOTE: Autonomous "custom element" belongs to
      # [FLOW_CONTENT, PHRASING_CONTENT, PALPABLE_CONTENT]

      VOID_ELEMENTS = Set.new(%w[area base br col embed hr img input link meta param source track wbr]).freeze

      INLINE_ELEMENTS_INCLUDING_VOID = Set.new(CONTENT_TYPES.select do |_name, types|
        # Split all table related elements.
        next false if types.include?(TABULAR_DATA)

        # RESTRICTION_PARENT_ELEMENT creates group for specific purpose.
        next false if types.include?(RESTRICTION_PARENT_ELEMENT)

        # Ignore meta elements
        next false if types.include?(METADATA_CONTENT)

        # Text-level contents are for decorating text like span
        next true if types.include?(TEXT_LEVEL_SEMANTICS)

        # Divide media to block
        if types.include?(EMBEDDED_CONTENTS)
          # Not divide content inside media
          next true if types.include?(RESTRICTED_TO_CHILD_OF_EMBEDDED)
          next false
        end

        if types.include?(FORMS)
          # Divide form element creating section
          next false if types.include?(SECTIONING_ROOT)

          # Divide "FORM"
          next false if types.include?(FORM_OWNER)

          # Ignore contents inputted by user
          next false if types.include?(ESCAPABLE_RAW_TEXT_ELEMENT)

          # Otherwise are grouped as FORM
          next true
        end

        false
      end.keys).freeze

      INLINE_ELEMENTS = (INLINE_ELEMENTS_INCLUDING_VOID - VOID_ELEMENTS).freeze
      EMPTY_ELEMENTS = (INLINE_ELEMENTS_INCLUDING_VOID & VOID_ELEMENTS).freeze

      # IGNORE_ELEMENTS doesn't scrape contents inside the tags
      IGNORE_ELEMENTS = Set.new(CONTENT_TYPES.select do |name, types|
        # meta should be ignored but require swapping.
        next true if name == 'meta'
        next true if types.include?(EMBEDDED_CONTENTS) && !types.include?(RESTRICTED_TO_CHILD_OF_EMBEDDED)
      end.keys).freeze

      # SKIP_ELEMENTS doesn't scrape and swap contents
      SKIP_ELEMENTS = Set.new(CONTENT_TYPES.select do |name, types|
        # iterate title to get content
        next false if name == 'title'
        next false if name == 'meta'

        next true  if types.include?(METADATA_CONTENT)
      end.keys).freeze

      # SKIP_ELEMENTS doesn't scrape and swap contents. But it scrape and swap tag's attributes like `placeholder`
      SKIP_ELEMENTS_WITHOUT_ATTRIBUTES = Set.new(CONTENT_TYPES.select do |name, types|
        # iterate title to get content
        next false if name == 'title'

        # Ignore contents inputted by user
        next true  if types.include?(ESCAPABLE_RAW_TEXT_ELEMENT)
      end.keys).freeze

      BLOCK_ELEMENTS = (Set.new(CONTENT_TYPES.keys) - INLINE_ELEMENTS - EMPTY_ELEMENTS - IGNORE_ELEMENTS - SKIP_ELEMENTS - SKIP_ELEMENTS_WITHOUT_ATTRIBUTES).freeze
    end
  end
end
